zone         = "ru-central1-a"
cloud_id     = "b1gn78tkp4ahcp204bqo"
folder_id    = "b1gnr9jhueppa1ibk2iu"
image_id     = "fd80iibe8asp4inkhuhr"
serv_acc_key = "/home/rel1ct0/yandex-cloud/serv_acc_key.json"
